/**
 * MSG91 OTP delivery. No-ops (logs a warning once) when MSG91_AUTH_KEY /
 * MSG91_TEMPLATE_ID are unset, so local/dev environments keep working exactly
 * as before this was added — debug-OTP-on-screen stays the fallback until a
 * real MSG91 account + DLT-approved template are configured.
 */

let warnedNotConfigured = false;

function isConfigured() {
  return Boolean(process.env.MSG91_AUTH_KEY && process.env.MSG91_TEMPLATE_ID);
}

/**
 * @param {string} phone 10-digit Indian mobile number (no country code)
 * @param {string} otp plain OTP value already generated by otpService.issueOtp
 * @returns {Promise<{ sent: boolean, reason?: string }>}
 */
export async function sendOtpSms(phone, otp) {
  if (!isConfigured()) {
    if (!warnedNotConfigured) {
      warnedNotConfigured = true;
      // eslint-disable-next-line no-console
      console.warn('[sms] MSG91_AUTH_KEY / MSG91_TEMPLATE_ID not set — skipping real SMS send (debug OTP only).');
    }
    return { sent: false, reason: 'NOT_CONFIGURED' };
  }

  const params = new URLSearchParams({
    otp,
    mobile: `91${phone}`,
    authkey: process.env.MSG91_AUTH_KEY,
    template_id: process.env.MSG91_TEMPLATE_ID,
  });

  try {
    const res = await fetch(`https://control.msg91.com/api/v5/otp?${params.toString()}`, {
      method: 'POST',
      headers: { accept: 'application/json' },
    });
    const body = await res.json().catch(() => ({}));
    if (res.ok && body?.type === 'success') {
      return { sent: true };
    }
    // eslint-disable-next-line no-console
    console.error('[sms] MSG91 send failed:', body?.message || res.status);
    return { sent: false, reason: body?.message || `HTTP_${res.status}` };
  } catch (e) {
    // eslint-disable-next-line no-console
    console.error('[sms] MSG91 request error:', e.message || e);
    return { sent: false, reason: 'NETWORK_ERROR' };
  }
}
