import { DataTypes, Model } from 'sequelize';

export function definePartner(sequelize) {
  class Partner extends Model {}
  Partner.init(
    {
      id: { type: DataTypes.STRING(64), primaryKey: true },
      phone: { type: DataTypes.STRING(16), allowNull: false },
      name: DataTypes.STRING(256),
      photoUrl: DataTypes.TEXT,
      photos: { type: DataTypes.JSON, defaultValue: [] },
      rating: { type: DataTypes.DECIMAL(3, 2), defaultValue: 4.8 },
      reviewsCount: { type: DataTypes.INTEGER, defaultValue: 0 },
      jobsCompleted: { type: DataTypes.INTEGER, defaultValue: 0 },
      isOnline: { type: DataTypes.BOOLEAN, defaultValue: false },
      skills: { type: DataTypes.JSON, defaultValue: [] },
      categories: { type: DataTypes.JSON, defaultValue: [] },
      walletBalance: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
      todayEarnings: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
      lifetimeEarnings: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
      bankName: DataTypes.STRING(256),
      bankAccount: DataTypes.STRING(64),
      verificationStatus: { type: DataTypes.STRING(32), defaultValue: 'Pending' },
      trainingProgress: { type: DataTypes.INTEGER, defaultValue: 0 },
      badges: { type: DataTypes.JSON, defaultValue: [] },
      strikeCount: { type: DataTypes.INTEGER, defaultValue: 0 },
      warningCount: { type: DataTypes.INTEGER, defaultValue: 0 },
      shadowBanned: { type: DataTypes.BOOLEAN, defaultValue: false },
      isBlocked: { type: DataTypes.BOOLEAN, defaultValue: false },
      isFrozen: { type: DataTypes.BOOLEAN, defaultValue: false },
      freezeUntil: { type: DataTypes.DATE, allowNull: true },
      archivedAt: { type: DataTypes.DATE, allowNull: true },
      accountStatus: { type: DataTypes.STRING(32), defaultValue: 'active' },
      primaryCity: { type: DataTypes.STRING(128), defaultValue: 'Rajahmundry' },
      serviceInnerRadiusKm: { type: DataTypes.INTEGER, defaultValue: 5 },
      serviceOuterRadiusKm: { type: DataTypes.INTEGER, defaultValue: 10 },
      allowOutOfStation: { type: DataTypes.BOOLEAN, defaultValue: false },
      totalJobsCount: { type: DataTypes.INTEGER, defaultValue: 0 },
      completedJobsCount: { type: DataTypes.INTEGER, defaultValue: 0 },
      rewardPoints: { type: DataTypes.INTEGER, defaultValue: 0 },
      latitude: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
      longitude: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
      referralCode: { type: DataTypes.STRING(32), allowNull: true },
      referredByPartnerId: { type: DataTypes.STRING(64), allowNull: true },
      referralCredited: { type: DataTypes.BOOLEAN, defaultValue: false },
      idType: { type: DataTypes.STRING(32), allowNull: true },
      idNumber: { type: DataTypes.STRING(64), allowNull: true },
      pincode: { type: DataTypes.STRING(6), allowNull: true },
      customCategoryRequest: { type: DataTypes.STRING(256), allowNull: true },
      description: { type: DataTypes.TEXT, allowNull: true },
    },
    {
      sequelize,
      modelName: 'Partner',
      tableName: 'partners',
      timestamps: true,
      indexes: [{ unique: true, fields: ['phone'], name: 'partners_phone_unique' }],
    },
  );
  return Partner;
}
